name: basic send email

on:
  pull_request:
    types: [ opened ]
  push:
  
jobs: 
  basic-send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v4
        with:
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.GHA_EMAIL_SECRET}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: elizabeth.gugliotti@noaa.gov
          # Required sender full name (address can be skipped):
          from: Elizabeth # <user@example.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
