# Builds the stock synthesis executables
# for mac, linux, windows
name: build-ss3

on:
  push:
  workflow_dispatch:
    # inputs:
      # # options: should be "win", "osx, "linux"
      # operating-sys:
      #   required: true
      #   type: string
jobs:
  build-ss3:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest}
    # Limit run time to 90 min to avoid wasting action minutes.
    # was set to 15 and then 30 minutes previously, but compiling admb
    # on mac took too long
    timeout-minutes: 90
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: checkout admb, windows
        if: matrix.config.os == 'windows-latest'
        uses: actions/checkout@v3
        with:
          repository: admb-project/admb
          path: admb
          ref: admb-13.1
       
#       - name: get microsoft visual c++
#         if: matrix.config.os == 'windows-latest'
#         uses: ilammy/msvc-dev-cmd@v1
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: make admb windows
        if: matrix.config.os == 'windows-latest'
        run: |
          cd admb 
          nmake
      - name: move admb and put in path windows
        if: matrix.config.os == 'windows-latest'
        run: |
          echo "D:\a\github-actions-test\github-actions-test\admb\build\admb\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
