name: email_when_close_pr

on:
  pull_request:
    types: [ closed ]

jobs: 
  email_when_close_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Request Number
        id: pr
        run: |
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get issues
        id: get-issues
        uses: mondeja/pr-linked-issues-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Print linked issue numbers
        run: echo ${{ steps.get-issues.outputs.issues }}   
        
#      - name: View PR author
#        run: |
#          echo ${{ github.event.pull_request.user.login }}
#          echo ${{ github.event.pull_request.user.email }}
  
      - name: get email
        id: test
        uses: evvanErb/get-github-email-by-username-action@v1.25
        with:
          github-username: ${{ github.triggering_actor }}
      
  # Use the output from the `test` step
      - name: Print the found email
        run: echo "The email is ${{ steps.test.outputs.email }}"
     
      - name: send email
        uses: cinotify/github-action@main
        with:
          to: ${{ steps.test.outputs.email }}
          subject: 'PR closed; reminder to fill out info in issue'
          body: "PR ${{ github.event.pull_request.number }} has been closed, please remember to move any pertinent information to the linked issues ${{ steps.get-issues.outputs.issues }}"
