name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Application Version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
      
#      - name: create tag
#        uses: mathieudutour/github-tag-action@v6.1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          custom_tag: ${{ steps.version.outputs.version }}
          
      - name: Build release artifact
        run: |
          echo "Hello, world!" > sample1.txt

      - name: Build another release artifact
        run: |
          echo "Hello, outer space!" > sample2.txt 
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }} Docs
          draft: false
          prerelease: false
          
      - name: Upload release artifact 1
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sample1.txt
          asset_name: sample1.txt
          asset_content_type: application/txt
      
      - name: Upload release artifact 2
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sample2.txt
          asset_name: sample2.txt
          asset_content_type: application/txt
