name: get-repo-and-site-name

on:
  push:

jobs:
    
  get-repo-site-name:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Set up R (needed for Rmd)
        uses: r-lib/actions/setup-r@v2
        
      - name: get repo name and github.io name
        run: |
          echo "site=${{ github.repository }}" >> "$GITHUB_ENV"
          echo "io_url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')" >> "$GITHUB_ENV"

      - name: Edit quarto.yml with correct site
        env: 
          SITE: ${{ env.site }}
          URL: ${{ env.io_url }}
        run: |
          text_file <- readLines("index.md")
          text_file[9] <- paste0("https://github.com/", Sys.getenv('SITE'))
          text_file[10] <- Sys.getenv('URL')
          text_file
        shell: Rscript {0}
